version: '3.8'

services:
  server:
    build:
      dockerfile: Dockerfile.local
      context: ./
    container_name: ddd_practice
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - '80:80'
    volumes:
      - ./src:/app/src
    command:
      - "npm"
      - "run"
      - "start:local:dev"

  mysql:
    container_name: mysql_db
    image: mysql:8.0
    ports:
      - "3308:3306"
    restart: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practice
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      TZ: Asia/Seoul
